### ISSUE TITLE
I don't understand why we checkout and imediately return worker to pool

### ISSUE THREAD

**Issue by bryanhuntesl** [esl/ex_rabbit_pool#17]
https://github.com/esl/ex_rabbit_pool/blob/6bae655b38e0e102bd12911a735e44ddcbb46e36/lib/ex_rabbit_pool.ex#L21-L23

**Comment by bryanhuntesl** [comment]
@gausby was also curious about this

**Comment by bryanhuntesl** [comment]
Like how come it's not just using `:poolboy:transaction`

**Comment by sescobb27** [comment]
@bryanhuntesl because we only care about the `channels` pool inside each worker, with a transaction we will block the worker for being pick up from the `:poolboy`'s pool, so for example if we have 2 connection workers and we have many processes (10 processes e.g requests) asking for channels to push a message through, only 2 client processes could grab a connection at the same time and then a channel out of those connections. with this approach, each process can pick up a worker and then ask that worker for a channel, in this case, it will be up to the worker to return a channel or make the client process wait for one when they get released.

**Comment by bryanhuntesl** [comment]
Clarified by #20
